
import { Category} from './category';
import { Question } from './question';

 
export const CATEGORIES: Category[] =  [
    { id: 1,
      category: "All about June",
      description: "It's my birthday month, so why not?",
      progress: 0,
      questions: [
        {
          id: 1,
          text: "Which two presidents were born in June?",
          bonusText: "",
          imageLink: "",
          hint: "Both presidents served after 1980.",
          answer: "George H.W. Bush (12th) and Donald Trump (14th)",
          bonusAnswer: "",
          points: 2,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 2,
          text: "Which two tennis Grand Slam tournaments are played in June?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "French Open and Wimbledon",
          bonusAnswer: "",
          points: 2,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 3,
          text: "The Smithsonian was founded by James Smithson in 1829. What day was it founded?<br>A) 3  B) 11  C) 24  D) 27",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "D) 27",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 4,
          text: "Speaking of the best day of the year, which of these famous people shares my birthday?<br>A) Helen Keller  B) JJ Abrams  C) Ross Perot  D) Vera Wang",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "All of them! (one point for each)",
          bonusAnswer: "",
          points: 999999,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 5,
          text: "Which of these is one of the birth flowers for June? <br>A) Rose  B) Marigold  C) Lily D) Poppy",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "A) Rose",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 6,
          text: "What did Governor John Winthrop of Massachusets introduce on this day in 1630 that transformed dining in America forever?",
          bonusText: "",
          imageLink: "",
          hint: "This tool was considered sacrilegious because God intended us to use our hands",
          answer: "The fork",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 7,
          text: "According to Icelandic folklore, what should people do on June 24th (Midsummer) to secure luck in the year to come? <br> A) Burn old fishing boats on a pyre  B) Bathe in morning dew  C) Sleep with flower crown under pillow  D) Walk barefoot on hot coals",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "B) Bathe in morning dew",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 8,
          text: "What was patented by Samuel Morse on June 20th, 1840?<br>A) Morse Code  B) Electrographic Vote Recorder  C) Telegraph  D) Telegraph wire",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "A) Morse Code",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 9,
          text: "True or False - No other month in the year begins on the same day of the week as June.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 10,
          text: "June's full moon gets its name from the Algonquin, Ojibwe, Dakota, and Lakota peoples, to mark the ripening of what \“June-bearing\” fruit?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Strawberry Moon",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 2,
      category: "Tour de France",
      description: "It starts tomorrow!",
      progress: 0,
      questions: [
        {
          id: 11,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 12,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 13,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 14,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 15,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 16,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 17,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 18,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 19,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 20,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 3,
      category: "Toy Story Characters",
      description: "I show a picture and you name the character",
      progress: 0,
      questions: [
        {
          id: 21,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 22,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 23,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 24,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 25,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 26,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 27,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 28,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 29,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 30,
          text: "",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 4,
      category: "Rebus Puzzles",
      description: "Can you figure it out?",
      progress: 0,
      questions: [
        {
          id: 31,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-puzzle.png?w=1044",
          hint: "",
          answer: "Green with envy",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 32,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebuspuzzle.png?w=1044",
          hint: "",
          answer: "Split pea soup",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 33,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-2puzzle.png?w=1044",
          hint: "",
          answer: "For once in my life",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 34,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-3puzzle.png?w=1044",
          hint: "",
          answer: "What goes up must come down",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 35,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-4puzzle.png?w=1044",
          hint: "",
          answer: "Overseas travel",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 36,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-5puzzle.png?w=1044",
          hint: "",
          answer: "Win with ease",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 37,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-9puzzle.png?w=1044",
          hint: "",
          answer: "Metaphor",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 38,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-6puzzle.png?w=1044",
          hint: "",
          answer: "Split level",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 39,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-7puzzle.png?w=1044",
          hint: "",
          answer: "Try to understand",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 40,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-8puzzle.png?w=1044",
          hint: "",
          answer: "Summer",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 5,
      category: "For the cicadas",
      description: "Trivia from 2004",
      progress: 0,
      questions: [
        {
          id: 41,
          text: "What Jeopardy record did Ken Jennings set in 2004, which has not been surpassed?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Longest win streak (74 wins)",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 42,
          text: "The Summer Olympics were held in 2004 in what city?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Athens, Greece",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 43,
          text: "Who won the Superbowl, World Series, NBA Championship, and Stanley Cup in 2004?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "New England Patriots, Boston Red Sox, Detroit Pistons, Tampa Bay Lightning",
          bonusAnswer: "",
          points: 4,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 44,
          text: "Which movie won the Oscar for Best Picture in 2004?<br> A) Lost in Translation  B) Mystic River  C) The Lord of the Rings: The Return of the King  D) Master and Commander: The Far Side of the World E) Seabiscuit",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "C) The Lord of the Rings: The Return of the King",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 45,
          text: "Which network received the most nominations and awards at the Emmmy Awards?<br> A) CBS  B) ABC  C) NBC  D) HBO",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "D) HBO",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 46,
          text: "What business magnate and television personality was sentenced to five months in prison for lying to federal investigators about a well-timed stock sale?",
          bonusText: "",
          imageLink: "",
          hint: "Her friendship with Snoop Dog is a \"good thing\"",
          answer: "Martha Stewart",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 47,
          text: "What social network was launched on February 4, 2004?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Facebook",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 48,
          text: "What sequal was the highest grossing movie of 2004?",
          bonusText: "",
          imageLink: "",
          hint: "This family friendly moview probably made the competition green with envy",
          answer: "Shrek 2",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 49,
          text: "How much did people who \"got a car\" from Oprah on September 14, 2004 have to pay in taxes or forfeit the gift?<br>A) $7,000  B) 2,000  C) zero  D) $5,000",
          bonusText: "",
          imageLink: "https://media.giphy.com/media/26gsiCIKW7ANEmxKE/source.gif",
          hint: "",
          answer: "A) $7,000",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 50,
          text: "What was the cost of a Superbowl ad in 2004?<br> A) $1.5 million B) $3.2 million  C) $2.3 million  D) $2.8 million",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "C) $2.3 million",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    }
  ]