
import { Category} from './category';
import { Question } from './question';

 
export const CATEGORIES: Category[] =  [
    { id: 1,
      category: "All about June",
      description: "It's my birthday month, so why not?",
      progress: 0,
      questions: [
        {
          id: 1,
          text: "Which two presidents were born in June?",
          bonusText: "",
          imageLink: "",
          hint: "Both presidents served after 1980.",
          answer: "George H.W. Bush (12th) and Donald Trump (14th)",
          bonusAnswer: "",
          points: 2,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 2,
          text: "Which two tennis Grand Slam tournaments are played in June?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "French Open and Wimbledon",
          bonusAnswer: "",
          points: 2,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 3,
          text: "The Smithsonian was founded by James Smithson in 1829. What day was it founded?<div class=\"multiple-choice\"> <dl><dt>A) 3</dt><dt>B) 11</dt><dt>C) 24</dt><dt>D) 27</dt></dl></div>",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "D) 27",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 4,
          text: "Speaking of the best day of the year, which of these famous people shares my birthday?<dl><dt>A) Helen Keller</dt><dt>B) JJ Abrams</dt><dt>C) Ross Perot</dt><dt>D) Vera Wang</dt></dl>",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "All of them! (one point for each)",
          bonusAnswer: "",
          points: 999999,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 5,
          text: "Which of these is one of the birth flowers for June? <dl><dt>A) Rose</dt><dt>B) Marigold</dt><dt>C) Lily</dt><dt>D) Poppy</dt></dl>",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "A) Rose",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 6,
          text: "What did Governor John Winthrop of Massachusets introduce on this day in 1630 that transformed dining in America forever?",
          bonusText: "",
          imageLink: "",
          hint: "This tool was considered sacrilegious because God intended us to use our hands",
          answer: "The fork",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 7,
          text: "According to Icelandic folklore, what should people do on June 24th (Midsummer) to secure luck in the year to come? <dl><dt>A) Burn old fishing boats on a pyre</dt><dt>B) Bathe in morning dew</dt><dt>C) Sleep with flower crown under pillow</dt><dt>D) Walk barefoot on hot coals</dt></dl>",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "B) Bathe in morning dew",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 8,
          text: "What was patented by Samuel Morse on June 20th, 1840?<dl><dt>A) Morse Code</dt><dt>B) Electrographic Vote Recorder</dt><dt>C) Telegraph</dt><dt>D) Telegraph wire</dt></dl>",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "A) Morse Code",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 9,
          text: "True or False - No other month in the year begins on the same day of the week as June.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 10,
          text: "June's full moon gets its name from the Algonquin, Ojibwe, Dakota, and Lakota peoples, to mark the ripening of what \“June-bearing\” fruit?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Strawberry Moon",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 2,
      category: "T/F about the TdeF",
      description: "True False about the Tour de France",
      progress: 0,
      questions: [
        {
          id: 11,
          text: "The longest Tour in 1926 was 5745 km",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 12,
          text: "The average rider will burn more than 200,000 calories during the race",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "False. They average 124,000 calories",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 13,
          text: "The oldest winner of the race was 37 years old.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "False. Fermin Lambot won in 1922. He was 32 years old.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 14,
          text: "The youngest winner was 19 years old.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True. Hernri Cornet won in 1904 at age 19.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 15,
          text: "There is a minimum weight for bikes.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True. They can't be lighter than 6.8 kg for safety reasons.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 16,
          text: "<a href=\"http://localhost:4200/song-player\">This song</a> was inspired by the Tour de France.",
          bonusText: "Who sings the song?",
          imageLink: "",
          hint: "",
          answer: "True",
          bonusAnswer: "Queen",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 17,
          text: "The average rider will go through 10 bike chains during the race.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "False. They'll go though an average of 3 chains.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 18,
          text: "A cyclist can win without winning any of the individual stages.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True. Greg LeMond won in 1990 without winning any stages.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 19,
          text: "Over the course of a Tour de France route, cyclists will sweat enough to flush a toilet 39 times.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True. And gross.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 20,
          text: "The Tour de France has the most spectators of any sporting event.",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "True. Over 12 million line the route each year.",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 3,
      category: "Toy Story Characters",
      description: "I show a picture and you name the character",
      progress: 0,
      questions: [
        {
          id: 21,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://wallpapercave.com/wp/wp1958547.jpg",
          hint: "",
          answer: "Buzz Lightyear",
          bonusAnswer: "Tim Allen",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 22,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://th.bing.com/th/id/OIP.wEQMdcwexFmFBi3Xk4UscwAAAA?pid=ImgDet&rs=1",
          hint: "",
          answer: "Hopper",
          bonusAnswer: "Kevin Spacey",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 23,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://th.bing.com/th/id/Raab1119fcc7120296333f94da8ff5ed5?rik=crPVsY%2fV0OxG8Q&riu=http%3a%2f%2fwww.hdwallpapersfreedownload.com%2fuploads%2flarge%2fcartoons%2ftoystory-1-2-3-jessie-free-wallpaper-background.jpg&ehk=NMLW4CMLitRdGNqvGa%2fxkxF35sQ9t0D6HHEurrT7ReM%3d&risl=&pid=ImgRaw",
          hint: "",
          answer: "Jesse",
          bonusAnswer: "Joan Cusack",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 24,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://th.bing.com/th/id/OIP.SKMHfd9Zn2My3gOD8ijTFQHaJl?pid=ImgDet&rs=1",
          hint: "",
          answer: "James Sullivan (aka Sulley)",
          bonusAnswer: "John Goodman",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 25,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://th.bing.com/th/id/R47178c3066ddd3b6fc38f983bab6aa24?rik=lsyMtY0fg%2f9%2f5g&riu=http%3a%2f%2fvignette2.wikia.nocookie.net%2fdisneyssebastiandory%2fimages%2fe%2fef%2fDory-FN.png%2frevision%2flatest%3fcb%3d20140131182445&ehk=k2sE%2bDwpx2G58CGm8Dj9JiNjarZR693fi4GvKDMhcJo%3d&risl=&pid=ImgRaw",
          hint: "",
          answer: "Dory",
          bonusAnswer: "Ellen Degeneres",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 26,
          text: "What's the character's name?",
          bonusText: "What is her profession?",
          imageLink: "https://partycity6.scene7.com/is/image/PartyCity/_pdp_sq_?$_1000x1000_$&$product=PartyCity/815711",
          hint: "",
          answer: "Edna Mode",
          bonusAnswer: "Superhero costume fashion designer",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 27,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://th.bing.com/th/id/R6565d19ac38f77c471156b6115b430fb?rik=zIM7UqKou86gQw&riu=http%3a%2f%2f1.bp.blogspot.com%2f-jNDltnql0C0%2fTzC4Jd1AIuI%2fAAAAAAAAEWM%2foeh2q3auP0U%2fs1600%2fdisney%2bcars%2btow%2bmater%2bwallpaper%2b4.jpg&ehk=uvD4jFaUIgmurBtdrXEdtiY3u6zawfXHoY%2bRnlWq%2b2I%3d&risl=&pid=ImgRaw",
          hint: "",
          answer: "Mater",
          bonusAnswer: "Larry the Cable Guy",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 28,
          text: "What's the character's name?",
          bonusText: "Who voiced the character?",
          imageLink: "https://th.bing.com/th/id/OIP.6AFJPYCZ1EuYCJ_5xmhAmgHaHj?pid=ImgDet&rs=1",
          hint: "",
          answer: "Remy",
          bonusAnswer: "Patton Oswalt",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 29,
          text: "What's the character's name?",
          bonusText: "What is this robot's job?",
          imageLink: "https://vignette.wikia.nocookie.net/wallethemovie/images/d/d2/Eve_Scanning.jpg/revision/latest?cb=20190720002834",
          hint: "",
          answer: "EVE",
          bonusAnswer: "To find self-sustaining plant life",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 30,
          text: "What's the character's name?",
          bonusText: "What does his collar do?",
          imageLink: "https://dogtails.dogwatch.com/wp-content/uploads/2011/03/dug_up.jpg",
          hint: "",
          answer: "Dug",
          bonusAnswer: "Gives him the ability to talk.",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 4,
      category: "Rebus Puzzles",
      description: "Can you figure it out?",
      progress: 0,
      questions: [
        {
          id: 31,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-puzzle.png?w=1044",
          hint: "",
          answer: "Green with envy",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 32,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebuspuzzle.png?w=1044",
          hint: "",
          answer: "Split pea soup",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 33,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-2puzzle.png?w=1044",
          hint: "",
          answer: "For once in my life",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 34,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-3puzzle.png?w=1044",
          hint: "",
          answer: "What goes up must come down",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 35,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-4puzzle.png?w=1044",
          hint: "",
          answer: "Overseas travel",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 36,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-5puzzle.png?w=1044",
          hint: "",
          answer: "Win with ease",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 37,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-9puzzle.png?w=1044",
          hint: "",
          answer: "Metaphor",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 38,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-6puzzle.png?w=1044",
          hint: "",
          answer: "Split level",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 39,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-7puzzle.png?w=1044",
          hint: "",
          answer: "Try to understand",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 40,
          text: "",
          bonusText: "",
          imageLink: "https://www.rd.com/wp-content/uploads/2020/10/Rebus-8puzzle.png?w=1044",
          hint: "",
          answer: "Summer",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    },
    { 
      id: 5,
      category: "For the cicadas",
      description: "Trivia from 2004",
      progress: 0,
      questions: [
        {
          id: 41,
          text: "What Jeopardy record did Ken Jennings set in 2004, which has not been surpassed?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Longest win streak (74 wins)",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 42,
          text: "The Summer Olympics were held in 2004 in what city?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Athens, Greece",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 43,
          text: "Who won the Superbowl, World Series, NBA Championship, and Stanley Cup in 2004?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "New England Patriots, Boston Red Sox, Detroit Pistons, Tampa Bay Lightning",
          bonusAnswer: "",
          points: 4,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 44,
          text: "Which movie won the Oscar for Best Picture in 2004?<br> A) Lost in Translation  B) Mystic River  C) The Lord of the Rings: The Return of the King  D) Master and Commander: The Far Side of the World E) Seabiscuit",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "C) The Lord of the Rings: The Return of the King",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 45,
          text: "Which network received the most nominations and awards at the Emmmy Awards?<br> A) CBS  B) ABC  C) NBC  D) HBO",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "D) HBO",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 46,
          text: "What business magnate and television personality was sentenced to five months in prison for lying to federal investigators about a well-timed stock sale?",
          bonusText: "",
          imageLink: "",
          hint: "Her friendship with Snoop Dog is a \"good thing\"",
          answer: "Martha Stewart",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 47,
          text: "What social network was launched on February 4, 2004?",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "Facebook",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 48,
          text: "What sequal was the highest grossing movie of 2004?",
          bonusText: "",
          imageLink: "",
          hint: "This family friendly moview probably made the competition green with envy",
          answer: "Shrek 2",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 49,
          text: "How much did people who \"got a car\" from Oprah on September 14, 2004 have to pay in taxes or forfeit the gift?<br>A) $7,000  B) 2,000  C) zero  D) $5,000",
          bonusText: "",
          imageLink: "https://media.giphy.com/media/26gsiCIKW7ANEmxKE/source.gif",
          hint: "",
          answer: "A) $7,000",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        },
        {
          id: 50,
          text: "What was the cost of a Superbowl ad in 2004?<br> A) $1.5 million B) $3.2 million  C) $2.3 million  D) $2.8 million",
          bonusText: "",
          imageLink: "",
          hint: "",
          answer: "C) $2.3 million",
          bonusAnswer: "",
          points: 1,
          asked: false,
          askOrder: -1,
          revealed: false
        }
      ]
    }
  ]