name: Crazy Albus testing Actions
run-name: Testing ssh action
on: [workflow_dispatch]
jobs:
    testSSH:
        runs-on: ubuntu-latest
        steps:
          - name: Run remote command via SSH
            uses: D3rHase/ssh-command-action@latest
            with:
              host: ${{ vars.IP }}
              port: ${{ vars.PORT }}
              user: ${{ secrets.USERNAME }}
              private_key: ${{ secrets.SSHKEY }}
              host_fingerprint: ${{ secrets.FINGERPRINT }}
              command: 
                echo 'composer install' &&
                echo 'drush cr' &&
                echo 'drush cim' &&
                cd public_html/web/themes/custom/base &&
                pwd &&
                echo *
